#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

riverctl map normal Super Return spawn kitty
riverctl map normal Super+Shift Return spawn neovide
riverctl map normal Super F spawn dolphin
riverctl map normal Super M spawn thunderbird
riverctl map normal Super B spawn "firefox --private-window"
riverctl map normal Super+Shift B spawn firefox
#riverctl map normal Super B spawn chromium
riverctl map normal Super Space spawn "fuzzel --font='Fira Code' --icon-theme='Papirus-Dark' -w 64 -b 222222ff -C aa0000ff -s aa0000ff -S ffffffff -M ffff00ff -B 2"
riverctl map normal Super V spawn "cliphist list | fuzzel --font='Fira Code' -d -w 64 -b 222222ff -C aa0000ff -s aa0000ff -S ffffffff -M ffff00ff -B 2 | cliphist decode | wl-copy"

riverctl map normal Super Q close
riverctl map normal Super L spawn "swaylock -c 222222"
for mode in normal locked
do
    riverctl map $mode Super+Shift Q exit
    riverctl map $mode Super+Control Q spawn "systemctl poweroff"
    riverctl map $mode Super+Control R spawn "systemctl reboot"
    riverctl map $mode Super+Control L spawn "systemctl suspend"
done

riverctl map normal Super Print spawn grim
riverctl map normal Super+Shift Print spawn 'grim -g "$(slurp)"'

riverctl map normal Super E focus-view next
riverctl map normal Super I focus-view previous

# view in the layout stack
riverctl map normal Super+Shift E swap next
riverctl map normal Super+Shift I swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super X zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super+Control N send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Control O send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift N send-layout-cmd rivertile "main-count -1"
riverctl map normal Super+Shift O send-layout-cmd rivertile "main-count +1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt N move left 100
riverctl map normal Super+Alt E move down 100
riverctl map normal Super+Alt I move up 100
riverctl map normal Super+Alt O move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Shift N snap left
riverctl map normal Super+Alt+Shift E snap down
riverctl map normal Super+Alt+Shift I snap up
riverctl map normal Super+Alt+Shift O snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Control N resize horizontal -100
riverctl map normal Super+Alt+Control E resize vertical 100
riverctl map normal Super+Alt+Control I resize vertical -100
riverctl map normal Super+Alt+Control O resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Z toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super+Control F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
    riverctl map $mode None XF86AudioMute         spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'
    riverctl map $mode None XF86AudioMicMute      spawn 'wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set 5%+'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0xaa0000
riverctl border-color-unfocused 0x444444
riverctl border-width 4

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make certain views start floating
#riverctl float-filter-add app-id float
#riverctl float-filter-add title "popup title with spaces"

# Set app-ids and titles of views which should use client side decorations
#riverctl csd-filter-add app-id "gedit"

riverctl focus-follows-cursor normal

# Keyboard layout
riverctl keyboard-layout -options "caps:backspace","grp:toggle" -variant ,colemak us,us

# Mouse stuff
touchpad=pointer-2362-8200-ASUP1205:00_093A:2008_Touchpad
riverctl input $touchpad natural-scroll enabled
riverctl input $touchpad click-method clickfinger
riverctl input $touchpad disable-while-typing enabled
riverctl input $touchpad tap enabled

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 4 -outer-padding 4 -main-ratio 0.5 &


/usr/lib/polkit-kde-authentication-agent-1 &
mako &
waybar -s ~/.config/waybar/style-river.css -c ~/.config/waybar/config-river &
nm-applet --indicator &
blueman-applet &
wlsunset -l 42.72 -L -73.68 &
wl-paste --watch cliphist store  &
cliphist wipe &

swaybg -m fill -i ~/MEGA/blobs-d-red.png &
swayidle before-sleep 'swaylock -c 222222' &
swayidle timeout 1800 'systemctl suspend' &
swayidle timeout 1500 'brightnessctl -s set 10%' resume 'brightnessctl -r' &

sleep 4s
bluetoothctl power off &
